require "language/node"

class Json2ts < Formula
  desc "Compile JSONSchema to TypeScript type declarations"
  homepage "https://github.com/bcherny/json-schema-to-typescript"
  url "https://registry.npmjs.org/json-schema-to-typescript/-/json-schema-to-typescript-14.0.0.tgz"
  sha256 "62a78b2afefdc20d7de806f4f192bd2d323f56c1fce616d77064e469b25df572"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "aa34de981fd77c1aa7b96ed3770d5de2d7d7dc79702d4918a3fe216c55701ecd"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "aa34de981fd77c1aa7b96ed3770d5de2d7d7dc79702d4918a3fe216c55701ecd"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "aa34de981fd77c1aa7b96ed3770d5de2d7d7dc79702d4918a3fe216c55701ecd"
    sha256 cellar: :any_skip_relocation, sonoma:         "ef25661a167ea7952589645e1fb987c43f6ed9375deb60c8d985e57d7818951c"
    sha256 cellar: :any_skip_relocation, ventura:        "ef25661a167ea7952589645e1fb987c43f6ed9375deb60c8d985e57d7818951c"
    sha256 cellar: :any_skip_relocation, monterey:       "ef25661a167ea7952589645e1fb987c43f6ed9375deb60c8d985e57d7818951c"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "aa34de981fd77c1aa7b96ed3770d5de2d7d7dc79702d4918a3fe216c55701ecd"
  end

  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    schema = <<~JSON
      {
        "title": "Example Schema",
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "age": {
            "description": "Age in years",
            "type": "integer",
            "minimum": 0
          },
          "hairColor": {
            "enum": ["black", "brown", "blue"],
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": ["firstName", "lastName"]
      }
    JSON

    typescript = <<~TS
      /* eslint-disable */
      /**
       * This file was automatically generated by json-schema-to-typescript.
       * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
       * and run json-schema-to-typescript to regenerate this file.
       */

      export interface ExampleSchema {
        firstName: string;
        lastName: string;
        /**
         * Age in years
         */
        age?: number;
        hairColor?: "black" | "brown" | "blue";
      }
    TS

    output = pipe_output("#{bin}/json2ts", schema)
    assert_equal output, typescript
  end
end
